### ISSUE TITLE
Site does not build locally

### ISSUE THREAD

**Issue by nathenharvey** [cfgmgmtcamp/cfgmgmtcamp.eu#11]
@toshywoshy do you have the IBM Cloud sponsor logo?  

I get the following when trying to build the site locally.

```
Building sites … 
ERROR 2019/01/03 07:56:46 Error while rendering "section" in "sponsors/": template: sponsors/list.html:29:39: executing "sponsors/list.html" at <resources.Get>: error calling Get: stat /Users/nathenharvey/projects/nathenharvey/cfgmgmtcamp.eu/themes/cfgmgmtcamp/assets/images/sponsors/ibmcloud.png: no such file or directory
Total in 135 ms
Error: Error building site: logged 1 error(s)
```

**Comment by nathenharvey** [comment]
The missing IBM Cloud logo was added in d4cc32.

There are still two additional failures because of missing images.  `chef.png` and `exoscale.png`

**Comment by toshywoshy** [comment]
@nathenharvey I think you're building with drafts enabled
The error is because of the missing sponsor logo of ibmcloud.png
I did not add the logo yet, because they're still a draft sponsor, we're awaiting confirmation

I am busy with adding the draft schedule, and I am not sure if all drafts will build yet
I will be adding more later in the day and sending a mail to review on the ml

**Comment by nathenharvey** [comment]
OK.  I do not know what it means to build with or without drafts enabled.  I would love to help out with edits and updates to the site including updating the README to describe the process for running the site locally and/or adding a CONTRIBUTING file.

I'll hold off on trying to make any updates though until you let us know that you are ready for us to do so.

**Comment by toshywoshy** [comment]
I have added all the draft buiding dependencies and added a make draft so I check in future that draft building works
Currently I use make to test all build, and as of now will check make draft
Hugo normally build all non-draft version, so if a file has draft: true it will not build that file, I use drafts to remind me or prepare some future work
How are you building?
I will update and add the README and CONTRIBUTING files, as I mentioned on the ML, I will add a wiki page so you can understand this better, currently I want to finish the draft schedule

**Comment by nathenharvey** [comment]
I'm building with `hugo server -D`

It looks like that is working now but, as you have noted, includes things that are not finalized like sponsors who are still in a "draft" status.

I will close this ticket as the site now builds and will hold off on any pull requests until you have notified us that you are ready for review.
