### ISSUE TITLE
Event popups display reused information

### ISSUE THREAD

**Issue by binford2k** [cfgmgmtcamp/cfgmgmtcamp.eu#32]
Reproduce:

1. Load Monday's schedule
    * https://cfgmgmtcamp.eu/schedule/monday/
2. Select the talk
    * `Incident Resolution as Code, Julien Pivotto`
3. Observe twitter handle
4. Close modal
5. Select the next talk
    * `Foreman and Kubevirt for Orchestrating a Virtualized environment over Containers, Boris Odnopozov`
6. Observe twitter handle
7. repeat sequentially and observe that the twitter handle will stay `@roidelapluie` until you hit another speaker with a handle.

I've experimentally verified that this happens any time that the speaker's profile has no twitter handle set, eg https://github.com/cfgmgmtcamp/cfgmgmtcamp.eu/blob/master/content/speaker/borisodnopozov.md

**Comment by binford2k** [comment]
Fixed in commit 212befa. Now it shows the twitter logo and a `@` link for empty handles. Not perfect, but way better, thanks @toshywoshy !

**Comment by toshywoshy** [comment]
Yes, I made a quick fix, will look at it later to solve it completely so it doesn't show even the icon or @ sign
